"""empty message

Revision ID: 029e0aadd309
Revises: 48dba38016ef
Create Date: 2023-05-17 13:32:01.547940

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "029e0aadd309"
down_revision = "48dba38016ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_services", schema=None) as batch_op:
        batch_op.alter_column(
            "user_name", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_services", schema=None) as batch_op:
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "user_name", existing_type=sa.VARCHAR(length=255), nullable=False
        )

    # ### end Alembic commands ###
