"""empty message

Revision ID: 80d2528e0842
Revises: 029e0aadd309
Create Date: 2023-05-17 13:44:38.067095

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "80d2528e0842"
down_revision = "029e0aadd309"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_services", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "unique_service_user", ["service_id", "user_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_services", schema=None) as batch_op:
        batch_op.drop_constraint("unique_service_user", type_="unique")

    # ### end Alembic commands ###
